# Generated by Django 3.2.5 on 2021-11-21 13:02

from django.db import migrations, models

import swapi_explorer.explorer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PeopleCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "csv_file",
                    models.FileField(
                        upload_to=swapi_explorer.explorer.models.collection_upload_to
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
